# Generated by Django 6.1.1 on 2026-10-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0002_cliente_password_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
    ]
